baseURL = "https://surveying-open-data-practices.github.io/sopd2020"
languageCode = "en-us"
title = "Surveying Open Data Practices in Research"
theme = "navigator-hugo"
summaryLength = 10
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
#[[Params.listeLangues]]
#code = "fr"
[[Params.listeLangues]]
code = "en"

# meta data
author = "Surveying Open Data Practices in Research"
description = "A project funded by the IDRC hosted at InSIS"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]

# Navbar Menus

[[menu.nav]]
name    = "about" 
weight  = 3
hasChildren = true

  [[menu.nav]]
  name    = "details"
  url     = "#about"
  parent  = "about"
  weight  = 1

  [[menu.nav]]
  name    = "values"
  url     = "#values"
  parent  = "about"
  weight  = 2
  
  [[menu.nav]]
  name    = "timeline"
  url     = "#timeline"
  parent  = "about"
  weight  = 3
  
  [[menu.nav]]
  name    = "team"
  url     = "#team"
  parent  = "about"
  weight  = 4

[[menu.nav]]
name    = "survey" 
weight  = 4
hasChildren = true

  [[menu.nav]]
  parent  = "survey"
  name    = "instrument"
  url     = "instrument"
  weight  = 1

  
  [[menu.nav]]
  parent  = "survey"
  name    = "design"
  url     = "design"
  weight  = 2
  
  
[[menu.nav]]
name    = "outputs" 
weight  = 5
url = "outputs"

[[menu.nav]]
name    = "blog"
url     = "blog"
weight  = 6

[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 7


# Footer Quick links Menu
[[menu.quicklink]]
name    = "template"
url     = "https://github.com/themefisher/navigator-hugo"
weight  = 1

[[menu.quicklink]]
name    = "images"
url     = "https://pixabay.com/"
weight  = 1



############# 1 - Site en ENGLISH
[Languages.en]
weight = 1
languageCode = "en-us"
title = "Surveying Open Data Practices in Research 2020"
dateFormat = "January 2, 2006"

home = "Home"
logo = "images/logo.png"
menufixed = true

footerDescription = "Surveying Open Data Practices will run from June 2020 - January 2021. The project is funded by the IDRC and hosted at InSIS, Oxford University."
footerQuicklinkTitle = "Resources"
footerAboutTitle = "About"
footerLicense = "Content published under CC-BY-4.0 except where original content licenses apply or when stated otherwise."

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Surveying Open Data Practices in Research 2020 - Africa"
description = "The Internet and progress in digital technologies are increasingly shifting the logic underlying science and research from closed to open systems. This change is affecting even the way data are managed, used and shared. This project will aim to capture the current landscape of open data practices in research.  The survey covers eight African countries including Uganda and Ethiopia from East Africa; Burkina Faso and Senegal from West Africa and Botswana, Malawi, Mozambique and Zimbabwe from Southern Africa."
button  = true
btnText = "Take the Survey"
btnURL  = "instrument"
videoThumb = "images/slider/video-player-thumb.png"
videoURL   = "https://youtu.be/Y1X0xtB_JcY"
videoMention = "Video used with courtesy of OCSDNet"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# About Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Open Science is more than open access to publications or data."
description = "Nowadays, it is recognized that, considered together, the three following dimensions of openness constitute Open Science: openness to publications and data, openness to society, and openness to excluded knowledges and epistemologies (Chan, Leslie et al. 2020). This project focuses on Open Data, a subset of Open Science that promotes the idea of research data being shared for scrutiny and re-analysis without unnecessary barriers. In recent years, an increasing number of funders, publishers and institutions have made commitments to fostering data sharing practices within the research community."
button  = true
btnText = "Read the full project proposal"
btnURL  = "https://zenodo.org/record/3961910#.Xx77jGMzais"

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = true
title   = "Recent News"

# Contact Section
[Languages.en.params.contact]
enable  = true
title   = "Contact Us."
subtitle= "We're really interested to hear from stakeholders and publish guest blog posts about open data practices in Africa. Please get in touch!"
twitter = "https://twitter.com/SODP_IDRC"
email = "sopd@googlegroups.com"


# Call to Action Section on Home Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/cta-1.jpg"
title   = "Tell us about your research data practices"
subtitle= "We aim to get wide participation from researchers and postgraduate students across the target countries (i.e. Uganda, Ethiopia, Burkina Faso, Senegal, Botswana, Malawi, Mozambique and Zimbabwe). If you are not from a country listed above, you can still participate. We will analyse all data and make the dataset available for others to analyze countries not covered in this project."
btnText = "Take the Survey"
link = "instrument"


# Gestion des langues : FR / EN / NL / DE
[Languages]


############ 1 - Site en FRANCAIS  [======================= THOMAS TRANSLATE FROM HERE ========================]
[Languages.fr]
weight = 2
languageCode = "fr-fr"
title = "Surveying Open Data Practices in Research 2020"
dateFormat = "January 2, 2006"

home = "Home"
logo = "images/logo.png"
menufixed = true

footerDescription = "Surveying Open Data Practices will run from June 2020 - January 2021. The project is funded by the IDRC and hosted at InSIS, Oxford University."
footerQuicklinkTitle = "Resources"
footerAboutTitle = "About"
footerLicense = "Content published under CC-BY-4.0 except where original content licenses apply or when stated otherwise."

# Hero Area Section
[Languages.fr.params.hero]
enable  = true
heading = "Surveying Open Data Practices in Research 2020 - Africa"
description = "The Internet and progress in digital technologies are increasingly shifting the logic underlying science and research from closed to open systems. This change is affecting even the way data are managed, used and shared. This project will aim to capture the current landscape of open data practices in research.  The survey covers eight African countries including Uganda and Ethiopia from East Africa; Burkina Faso and Senegal from West Africa and Botswana, Malawi, Mozambique and Zimbabwe from Southern Africa."
button  = true
btnText = "Take the Survey"
btnURL  = "instrument"
videoThumb = "images/slider/video-player-thumb.png"
videoURL   = "https://youtu.be/Y1X0xtB_JcY"
videoMention = "Video used with courtesy of OCSDNet"


# About Section
[Languages.fr.params.aboutSm]
enable  = true
title   = "Open Science is more than open access to publications or data."
description = "Nowadays, it is recognized that, considered together, the three following dimensions of openness constitute Open Science: openness to publications and data, openness to society, and openness to excluded knowledges and epistemologies (Chan, Leslie et al. 2020). This project focuses on Open Data, a subset of Open Science that promotes the idea of research data being shared for scrutiny and re-analysis without unnecessary barriers. In recent years, an increasing number of funders, publishers and institutions have made commitments to fostering data sharing practices within the research community."
button  = true
btnText = "Read the full project proposal"
btnURL  = "https://zenodo.org/record/3961910#.Xx77jGMzais"

# Blog Section On Homepage
[Languages.fr.params.blog]
enable  = true
title   = "Recent News"

# Contact Section
[Languages.fr.params.contact]
enable  = true
title   = "Contact Us."
subtitle= "We're really interested to hear from stakeholders and publish guest blog posts about open data practices in Africa. Please get in touch!"
twitter = "https://twitter.com/SODP_IDRC"
email = "sopd@googlegroups.com"

# Call to Action Section on About Page
[Languages.fr.params.cta]
enable  = true
bg      = "images/call-to-action/cta-1.jpg"
title   = "Tell us about your research data practices"
subtitle= "We aim to get wide participation from researchers and postgraduate students across the target countries (i.e. Uganda, Ethiopia, Burkina Faso, Senegal, Botswana, Malawi, Mozambique and Zimbabwe). If you are not from a country listed above, you can still participate. We will analyse all data and make the dataset available for others to analyze countries not covered in this project."
btnText = "Take the Survey"
link = "instrument"



